name: Test docker image

on:
  push:
    branches:
      - main

jobs:
  build_image_ubuntu:
    name: Build and upload alpine-based image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push alpine
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/str4ngeb0yz/destructivefarm:alpine
          file: Dockerfile.alpine

      - name: Image digests
        run: echo ${{ steps.docker_build.outputs.digest }}

  build_image_alpine:
    name: Build and upload debian-based image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/str4ngeb0yz/destructivefarm:latest,ghcr.io/str4ngeb0yz/destructivefarm:slim
          file: Dockerfile

      - name: Image digests
        run: echo ${{ steps.docker_build.outputs.digest }}
